from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

# Add scripts/ to sys.path so we can import sibling modules when run from repo root.
_SCRIPTS_DIR = Path(__file__).parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import parse_alloy_instance as pai
import instance_to_fixture as i2f


# AlloyRunner compilation and invocation

def _run_alloy(
    alloy_jar: Path,
    model_path: Path,
    run_name: str,
    output_xml: Path,
) -> None:
    if not alloy_jar.exists():
        raise FileNotFoundError(
            f"Alloy JAR not found at {alloy_jar}. "
        )

    output_xml.parent.mkdir(parents=True, exist_ok=True)

    # Use a per-run temp directory. The JARs -f flag wipes the entire output directory
    # before writing, which would delete previously generated XML files if we used the
    # shared alloy/instances/ dir directly for every run.
    with tempfile.TemporaryDirectory() as tmp_dir:
        result = subprocess.run(
            [
                "java", "-jar", str(alloy_jar),
                "exec",
                "-c", run_name,
                "-t", "xml",
                "-q",
                "-f",
                "-o", tmp_dir,
                str(model_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"Alloy CLI exec failed for '{run_name}':\n"
                f"stdout: {result.stdout}\nstderr: {result.stderr}"
            )

        # The JAR writes `<run_name>-solution-0.xml` into the temp dir.
        jar_output = Path(tmp_dir) / f"{run_name}-solution-0.xml"
        if jar_output.exists():
            shutil.move(str(jar_output), str(output_xml))
        elif not output_xml.exists():
            raise RuntimeError(
                f"Alloy produced no output for '{run_name}'. "
                f"Expected {jar_output.name} in temp dir. The run command may be UNSAT.\n"
                f"stdout: {result.stdout}\nstderr: {result.stderr}"
            )


# C# code generation

_CS_HEADER = """\
// AUTO-GENERATED by scripts/alloy_to_fixture.py  !do not edit!!.
// Source: alloy/static/predicates.als, scripts/alloy_test_expectations.yaml
// Regenerate: python scripts/alloy_to_fixture.py --repo-root .

using System.Collections.Generic;
using Bit.Core.AdminConsole.Repositories;
using Bit.Core.Repositories;
using Bit.Core.Vault.Repositories;
using Xunit;

namespace Bit.Infrastructure.IntegrationTest.Vault.Repositories;
"""

_CS_FIXTURE_DATA_OPEN = """\
/// <summary>
/// Fixture JSON embedded at codegen time. Keyed by Alloy run command name.
/// AlloyCipherFixtureHelpers.LoadFixture() reads from this dictionary.
/// </summary>
internal static class AlloyCipherFixtureData
{
    public static readonly Dictionary<string, string> Fixtures = new()
    {
"""

_CS_FIXTURE_DATA_CLOSE = """\
    };
}

"""

_CS_CLASS_OPEN = """\
///
/// Integration tests generated from Alloy model instances.
/// Each test recreates a concrete database state found by the Alloy Analyzer
/// and asserts that GetManyByUserIdAsync (the UserCipherDetails TVF) returns
/// the expected permission flags.
///
public class AlloyCipherFixtureTests
{
"""

_CS_CLASS_CLOSE = "}\n"

_COMMON_PARAMS = """\
        IUserRepository userRepository,
        IOrganizationRepository organizationRepository,
        IOrganizationUserRepository organizationUserRepository,
        ICollectionRepository collectionRepository,
        ICollectionCipherRepository collectionCipherRepository,
        IGroupRepository groupRepository,
        ICipherRepository cipherRepository"""

_COMMON_FIXTURE_SETUP = """\
        var fixture = AlloyCipherFixtureHelpers.LoadFixture("{name}");
        var (userId, cipherId) = await AlloyCipherFixtureHelpers.CreateEntitiesFromFixture(
            fixture, userRepository, organizationRepository, organizationUserRepository,
            collectionRepository, collectionCipherRepository, groupRepository, cipherRepository);
"""


def _generate_assertions(expected: dict) -> list[str]:
    """Generate xUnit assertion lines from the expected dict."""
    lines: list[str] = []
    can_see = expected.get("can_see")

    if can_see is True:
        lines.append(
            "        var details = results.FirstOrDefault(c => c.Id == cipherId);"
        )
        lines.append("        Assert.NotNull(details);")
    elif can_see is False:
        lines.append(
            "        Assert.DoesNotContain(results, c => c.Id == cipherId);"
        )
        # if can_see is false, remaining flags are irrelevant
        return lines
    else:
        # can_see is null - still need details for other assertions
        lines.append(
            "        var details = results.FirstOrDefault(c => c.Id == cipherId);"
        )

    for flag_key, prop_name in [
        ("can_edit",         "Edit"),
        ("can_view_password","ViewPassword"),
        ("can_manage",       "Manage"),
    ]:
        val = expected.get(flag_key)
        if val is True:
            lines.append(f"        Assert.True(details.{prop_name});")
        elif val is False:
            lines.append(f"        Assert.False(details.{prop_name});")

    return lines


def _generate_test_method(name: str, expected: dict) -> str:
    assertions = _generate_assertions(expected)
    lines = [
        "    [DatabaseTheory, DatabaseData]",
        f"    public async Task {name}_MatchesTvf(",
        _COMMON_PARAMS + ")",
        "    {",
        # Indent each setup line
        *[f"    {ln}" for ln in _COMMON_FIXTURE_SETUP.format(name=name).splitlines()],
        "",
        "        var results = await cipherRepository.GetManyByUserIdAsync(userId);",
        "",
        *assertions,
        "    }",
        "",
    ]
    return "\n".join(lines)


def generate_cs_file(fixtures: list[dict]) -> str:
    """
    Generate the full AlloyCipherFixtureTests.cs content from a list of fixture dicts.
    """
    parts = [_CS_HEADER, "\n"]

    # Embedded fixture data class
    parts.append(_CS_FIXTURE_DATA_OPEN)
    for fixture in fixtures:
        name = fixture["name"]
        json_str = json.dumps(fixture, separators=(",", ":"))
        # Escape """ inside the raw string literal (shouldn't appear in JSON but be safe)
        json_str = json_str.replace('"""', r'\"\"\"')
        parts.append(f'        ["{name}"] = """\n            {json_str}\n            """,\n')
    parts.append(_CS_FIXTURE_DATA_CLOSE)

    # Test class
    parts.append(_CS_CLASS_OPEN)
    for fixture in fixtures:
        parts.append(_generate_test_method(fixture["name"], fixture["expected"]))
    parts.append(_CS_CLASS_CLOSE)

    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate C# fixture tests from Alloy instances.")
    parser.add_argument("--repo-root", default=".", help="Path to the repository root.")
    parser.add_argument(
        "--skip-alloy", action="store_true",
        help="Skip running AlloyRunner; use existing XML files in alloy/instances/."
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Print test-subject atom derivation results for manual verification."
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    config    = i2f.load_config(repo_root)
    alloy_cfg = config["alloy"]

    alloy_jar     = repo_root / alloy_cfg["jar"]
    model_path    = repo_root / alloy_cfg["model"]
    instances_dir = repo_root / alloy_cfg["instances_dir"]
    fixtures_dir  = repo_root / alloy_cfg["fixtures_dir"]
    generated_cs  = repo_root / alloy_cfg["generated_cs"]

    # Load expectations
    expectations_path = repo_root / "scripts" / "alloy_test_expectations.yaml"
    with open(expectations_path) as f:
        expectations_cfg = yaml.safe_load(f)
    runs: dict = expectations_cfg.get("runs", {})

    instances_dir.mkdir(parents=True, exist_ok=True)
    fixtures_dir.mkdir(parents=True, exist_ok=True)

    all_fixtures: list[dict] = []

    for run_name, expectation in runs.items():
        xml_path     = instances_dir / f"{run_name}.xml"
        fixture_path = fixtures_dir  / f"{run_name}.json"

        print(f"[{run_name}]")

        # Step 1: Run the Alloy Analyzer (unless skipped)
        if not args.skip_alloy:
            print(f"  Running Alloy CLI...", flush=True)
            _run_alloy(alloy_jar, model_path, run_name, xml_path)
        elif not xml_path.exists():
            print(f"  WARNING: {xml_path} not found, skipping.", flush=True)
            continue

        # Step 2: Parse instance XML
        print(f"  Parsing {xml_path.name}...", flush=True)
        parsed = pai.parse_instance(xml_path)

        # Step 3: Build fixture
        print(f"  Building fixture...", flush=True)
        fixture = i2f.build_fixture(
            parsed, run_name, expectation, config, verbose=args.verbose
        )

        # Step 4: Write fixture JSON
        with open(fixture_path, "w") as f:
            json.dump(fixture, f, indent=2)
        print(f"  Wrote {fixture_path.name}", flush=True)

        all_fixtures.append(fixture)

    if not all_fixtures:
        print("No fixtures generated. Exiting.")
        return

    # Step 5: Generate C# test file
    print(f"\nGenerating {generated_cs.name}...", flush=True)
    generated_cs.parent.mkdir(parents=True, exist_ok=True)
    cs_content = generate_cs_file(all_fixtures)
    with open(generated_cs, "w") as f:
        f.write(cs_content)
    print(f"Wrote {generated_cs} ({len(all_fixtures)} test methods).")


if __name__ == "__main__":
    main()
